// TODO: Include packages needed for this application
const generateMarkdown = require("./generateMarkdown");

// TODO: Create an array of questions for user input
const questions = [
    "What is your name?",
  "How old are you?",
  "Where are you from?",
  "What is your favorite hobby?",
  "Do you have any pets?",
  "What programming languages do you know?",
  "What is your favorite food?",
  "What is your favorite animal?"
];

// TODO: Create a function to write README file
function writeToFile(fileName, data) {
    generateMarkdown.writeToFile(fileName, data, err => {
        if (err) {
          console.error("Error writing to file:", err);
          return;
        }
        console.log(`Data has been written to ${fileName} successfully.`);
      });
}

// TODO: Create a function to initialize app
function init() {
    const readmeData = `# My App

This is a README file generated by my app.

## Usage

1. Install dependencies: \`npm install\`
2. Run the app: \`node app.js\`
3. Follow the prompts to input your information.
`;

    const fileName = "README.md";
    writeToFile(fileName, readmeData);
}

// Function call to initialize app
init();
